[project]
name = "helper-tools"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyinstaller>=6.12.0",
    "yt-dlp>=2025.2.19",
]
